
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHeaderView, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")

        Form.setStyleSheet(u"")
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 111, 41))
        self.label.setLayoutDirection(Qt.LeftToRight)
        self.label.setStyleSheet(u"font-size: 18px")
        self.label.setAlignment(Qt.AlignCenter)
        self.descricao_input = QLineEdit(Form)
        self.descricao_input.setObjectName(u"descricao_input")
        self.descricao_input.setGeometry(QRect(120, 10, 121, 31))
        self.line = QFrame(Form)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(250, 0, 20, 71))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(250, 10, 111, 41))
        self.label_2.setLayoutDirection(Qt.LeftToRight)
        self.label_2.setStyleSheet(u"font-size: 18px")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.valor_input = QLineEdit(Form)
        self.valor_input.setObjectName(u"valor_input")
        self.valor_input.setGeometry(QRect(340, 10, 131, 31))
        self.line_3 = QFrame(Form)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(473, 0, 20, 71))
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.botao_gasto = QPushButton(Form)
        self.botao_gasto.setObjectName(u"botao_gasto")
        self.botao_gasto.setGeometry(QRect(500, 10, 111, 41))
        self.botao_gasto.setStyleSheet(u"background-color: red; color: black")
        self.botao_lucro = QPushButton(Form)
        self.botao_lucro.setObjectName(u"botao_lucro")
        self.botao_lucro.setGeometry(QRect(620, 10, 111, 41))
        self.botao_lucro.setStyleSheet(u"background-color: green; color: black")
        self.remover_botao = QPushButton(Form)
        self.remover_botao.setObjectName(u"remover_botao")
        self.remover_botao.setGeometry(QRect(740, 10, 111, 41))
        self.line_12 = QFrame(Form)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(-10, 0, 20, 71))
        self.line_12.setFrameShape(QFrame.Shape.VLine)
        self.line_12.setFrameShadow(QFrame.Shadow.Sunken)
        self.tableWidget = QTableWidget(Form)
        if (self.tableWidget.columnCount() < 2):
            self.tableWidget.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setTextAlignment(Qt.AlignLeading|Qt.AlignTop);
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(-10, 70, 891, 341))
        self.total = QLineEdit(Form)
        self.total.setObjectName(u"total")
        self.total.setGeometry(QRect(140, 430, 101, 28))
        self.total.setStyleSheet(u"border: none; font-size: 20px")
        self.total.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.line_6 = QFrame(Form)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(870, 0, 20, 431))
        self.line_6.setFrameShape(QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 420, 101, 41))
        self.label_3.setLayoutDirection(Qt.LeftToRight)
        self.label_3.setStyleSheet(u"font-size: 20px")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.line_8 = QFrame(Form)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(90, 410, 20, 81))
        self.line_8.setFrameShape(QFrame.Shape.VLine)
        self.line_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_14 = QFrame(Form)
        self.line_14.setObjectName(u"line_14")
        self.line_14.setGeometry(QRect(0, 60, 871, 20))
        self.line_14.setFrameShape(QFrame.Shape.HLine)
        self.line_14.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_5 = QFrame(Form)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(0, 400, 871, 20))
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_13 = QFrame(Form)
        self.line_13.setObjectName(u"line_13")
        self.line_13.setGeometry(QRect(880, 430, 3, 61))
        self.line_13.setFrameShape(QFrame.Shape.VLine)
        self.line_13.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_9 = QFrame(Form)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(0, 410, 20, 81))
        self.line_9.setFrameShape(QFrame.Shape.VLine)
        self.line_9.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_15 = QFrame(Form)
        self.line_15.setObjectName(u"line_15")
        self.line_15.setGeometry(QRect(0, 70, 20, 21))
        self.line_15.setFrameShape(QFrame.Shape.VLine)
        self.line_15.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(210, 420, 61, 41))
        self.label_4.setLayoutDirection(Qt.LeftToRight)
        self.label_4.setStyleSheet(u"font-size: 20px")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.texto_dinheiroo = QLabel(Form)
        self.texto_dinheiroo.setObjectName(u"texto_dinheiroo")
        self.texto_dinheiroo.setGeometry(QRect(100, 418, 41, 51))
        self.texto_dinheiroo.setLayoutDirection(Qt.LeftToRight)
        self.texto_dinheiroo.setStyleSheet(u"font-size: 20px")
        self.texto_dinheiroo.setAlignment(Qt.AlignCenter)
        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"Descrição ", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Valor  : ", None))
        self.botao_gasto.setText(QCoreApplication.translate("Form", u"Adicionar Gasto", None))
        self.botao_lucro.setText(QCoreApplication.translate("Form", u"Adicionar Lucro", None))
        self.remover_botao.setText(QCoreApplication.translate("Form", u"Remover ", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Form", u"Descrição", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Form", u"Valor", None));
        self.total.setText(QCoreApplication.translate("Form", "0", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Total : ", None))
        self.texto_dinheiroo.setText(QCoreApplication.translate("Form", u"R$", None))

    # retranslateUi
